export const DELIVERY_OFFER_STATUS = {
  OFFERED: 'OFFERED',
  ACCEPTED: 'ACCEPTED',
  REJECTED: 'REJECTED',
  EXPIRED: 'EXPIRED',
  CANCELLED: 'CANCELLED',
  SUPERSEDED: 'SUPERSEDED',
};

export const DELIVERY_REJECTION_REASONS = [
  'AMOUNT_TOO_LOW',
  'DISTANCE_TOO_FAR',
  'UNAVAILABLE',
  'VEHICLE_ISSUE',
  'OTHER',
];
