export const PROCUREMENT_PLAN_STATUS = {
  DRAFT: 'DRAFT',
  CONFIRMED: 'CONFIRMED',
  CANCELLED: 'CANCELLED',
};

export const ACTIVE_PROCUREMENT_PLAN_STATUSES = [
  PROCUREMENT_PLAN_STATUS.DRAFT,
  PROCUREMENT_PLAN_STATUS.CONFIRMED,
];
