export const PURCHASE_REQUEST_STATUS = {
  DRAFT: 'DRAFT',
  SUBMITTED: 'SUBMITTED',
  ACKNOWLEDGED: 'ACKNOWLEDGED',
  PARTIALLY_FULFILLED: 'PARTIALLY_FULFILLED',
  FULFILLED: 'FULFILLED',
  CANCELLED: 'CANCELLED',
};

export const EDITABLE_PURCHASE_REQUEST_STATUSES = [
  PURCHASE_REQUEST_STATUS.DRAFT,
];

export const CANCELLABLE_PURCHASE_REQUEST_STATUSES = [
  PURCHASE_REQUEST_STATUS.DRAFT,
  PURCHASE_REQUEST_STATUS.SUBMITTED,
  PURCHASE_REQUEST_STATUS.ACKNOWLEDGED,
];

export const RECEIVABLE_PURCHASE_REQUEST_STATUSES = [
  PURCHASE_REQUEST_STATUS.ACKNOWLEDGED,
  PURCHASE_REQUEST_STATUS.PARTIALLY_FULFILLED,
];

export const TERMINAL_PURCHASE_REQUEST_STATUSES = [
  PURCHASE_REQUEST_STATUS.FULFILLED,
  PURCHASE_REQUEST_STATUS.CANCELLED,
];
