export const SUPPLIER_ORDER_STATUS = {
  PENDING: 'PENDING',
  ASSIGNED: 'ASSIGNED',
  SENT: 'SENT',
  ACKNOWLEDGED: 'ACKNOWLEDGED',
  CONFIRMED: 'CONFIRMED',
  PROCESSING: 'PROCESSING',
  READY: 'READY',
  COLLECTED: 'COLLECTED',
  RECEIVED_AT_WAREHOUSE: 'RECEIVED_AT_WAREHOUSE',
  CANCELLED: 'CANCELLED',
  REJECTED: 'REJECTED',
};

export const SUPPLIER_ORDER_TRANSITIONS = {
  PENDING: ['ASSIGNED', 'CANCELLED'],
  ASSIGNED: ['SENT', 'CANCELLED', 'REJECTED'],
  SENT: ['ACKNOWLEDGED', 'REJECTED', 'CANCELLED'],
  ACKNOWLEDGED: ['CONFIRMED', 'REJECTED', 'CANCELLED'],
  CONFIRMED: ['PROCESSING', 'REJECTED', 'CANCELLED'],
  PROCESSING: ['READY', 'REJECTED', 'CANCELLED'],
  READY: ['COLLECTED', 'CANCELLED'],
  COLLECTED: ['RECEIVED_AT_WAREHOUSE'],
  RECEIVED_AT_WAREHOUSE: [],
  CANCELLED: [],
  REJECTED: [],
};
