export const SUPPLIER_STATUS = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
};

export const SUPPLIER_STATUS_TRANSITIONS = {
  [SUPPLIER_STATUS.PENDING]: [SUPPLIER_STATUS.APPROVED],
  [SUPPLIER_STATUS.APPROVED]: [SUPPLIER_STATUS.ACTIVE],
  [SUPPLIER_STATUS.ACTIVE]: [SUPPLIER_STATUS.INACTIVE],
  [SUPPLIER_STATUS.INACTIVE]: [SUPPLIER_STATUS.ACTIVE],
};
