const fs = require('fs');
const path = require('path');
const out = path.join(__dirname, '..', 'BACKEND_DOCUMENTATION.md');
const L = [];
const w = (s = '') => L.push(s);

w('');
w('## 16. Complete Background Job Inventory');
w('');
w('### 16.1 Startup Gates (`server.js`)');
w('');
w('| Component | Gate |');
w('|-----------|------|');
w('| Cron | `NODE_ENV!=test`, `ENABLE_CRON!=false`, and (`ENABLE_CRON=true` OR `NODE_ENV=production`) |');
w('| Workers (`workers/index.js`) | `ENABLE_WORKERS=true` |');
w('');
w('### 16.2 Cron Jobs');
w('');
w('| Job | Schedule | Behavior | Status |');
w('|-----|----------|----------|--------|');
w('| Payment reconcile | every 5m | Stuck PENDING/INITIATED payments >15m -> FAILED; restoreStock | Partial — stock inflate risk for reserved online |');
w('| DB lock cleanup | every 10m | Cleanup | Wired when cron starts |');
w('| cancelPendingOrders | — | Cancel PENDING >30m | **Not scheduled** |');
w('| checkCreditLimits | — | Log low credit | **Not scheduled** |');
w('| cleanupLogs / syncInventory | — | Console stubs | **Not scheduled** |');
w('');
w('### 16.3 BullMQ Queues');
w('');
w('| Queue | Producer | Consumer | Status |');
w('|-------|----------|----------|--------|');
w('| `post-payment` | queueManager | postPayment.worker | Queued work; worker **not started by server** (orphaned) |');
w('| `post-order` | queueManager | postOrder.worker | Orphaned; also imports missing order.service exports |');
w('| `notification` | notification.service | workers/index socket emit | Partial |');
w('| `email` | — | mock log | Stub |');
w('| `inventory` / `payment` / `audit` / `webhook` / `image-processing` / `data-archival` | various | stubs | Stub (`USE_REAL_QUEUE=false` for module queues) |');
w('');
w('### 16.4 Post-Payment Intended Work (if worker ran)');
w('');
w('1. `generateInvoice(orderId)`');
w('2. `autoAssignDelivery(orderId)`');
w('');
w('---');
w('');
w('## 17. Complete Cache Inventory');
w('');
w('### 17.1 Redis Key Patterns');
w('');
w('| Key | Purpose | TTL |');
w('|-----|---------|-----|');
w('| `payment:lock:{orderId}` | Payment mutex | ~60s |');
w('| `payment:processed:{razorpay_payment_id}` | Replay protection | 24h |');
w('| `webhook:processed:{id}` | Webhook idempotency | 60s then 24h |');
w('| `credit:reversal:{orderId}:{userId}` | Credit reverse idempotency | 1h |');
w('| `refund:{orderId}:{userId}` | Refund idempotency | 24h |');
w('| `inventory:reservation:{orderId}` | Soft stock hold | 900s |');
w('| `fraud:*` / `fraud:blocked:*` | Fraud counters/blocks | varies |');
w('| `cache:{url}` | HTTP GET cache middleware | configurable |');
w('| Idempotency keys/locks | Mutation dedupe | ~15s lock / 24h result |');
w('| `security:events` | Security audit list | — |');
w('| Rate-limit keys | express-rate-limit Redis store | window |');
w('');
w('### 17.2 Non-Redis');
w('');
w('- In-process Map cache service.');
w('- Product list memory cache 5 minutes.');
w('');
w('---');
w('');
w('## 18. Complete Security Inventory');
w('');
w('### 18.1 JWT');
w('');
w('- Access 15m; refresh DB-backed 7d with rotation + family reuse detection.');
w('- Session binding via `activeSessionId` / `SESSION_REPLACED`.');
w('- Both access and refresh JWTs signed with `JWT_SECRET` (refresh secret unused).');
w('');
w('### 18.2 CSRF');
w('');
w('- Double-submit: cookie `csrf-token` + header `x-csrf-token` (or body `_csrf`).');
w('- Cookie httpOnly — clients must use response body token for header.');
w('- Skipped for safe methods, webhooks/callbacks, public auth paths; test env unless enforced.');
w('');
w('### 18.3 CORS');
w('');
w('- Allowlist: localhost 5173-5175/3000, `*.vercel.app`, FRONTEND_URL.');
w('- `credentials: true`; methods GET/POST/PUT/PATCH/DELETE/OPTIONS.');
w('- Headers include Authorization, x-csrf-token, idempotency-key, x-razorpay-signature.');
w('');
w('### 18.4 Helmet');
w('');
w('- CSP allowing Razorpay; HSTS 1y; frameguard sameorigin; noSniff; xssFilter; hide X-Powered-By.');
w('');
w('### 18.5 Rate Limiting (Redis)');
w('');
w('| Limiter | Window | Max | Applied |');
w('|---------|--------|-----|---------|');
w('| apiLimiter | 15m | 1000 | All `/api` |');
w('| authLimiter | 15m | 5 failed | Auth sensitive |');
w('| paymentLimiter | 15m | 5 failed | Payments |');
w('| orderLimiter | 5m | 10 | POST /orders |');
w('');
w('Skip: test env, localhost, automated-test headers; auth/payment skip when AUTH_STRICT_MODE=false.');
w('');
w('### 18.6 Input Sanitization');
w('');
w('- mongoSanitize: strip `$` / `.` keys.');
w('- xssSanitize: escape strings.');
w('- Body 10MB; parameterLimit 100.');
w('');
w('### 18.7 File Upload Security');
w('');
w('- MIME/ext allowlists; magic-byte checks; filename sanitize; path traversal blocked.');
w('- Max 10MB, <=5 files; payment proof 5MB jpg/png/pdf.');
w('- Storage: Cloudinary / S3 / local disk.');
w('');
w('### 18.8 Redis / BullMQ / Webhooks / Secrets');
w('');
w('- Redis: locks, fraud, rate limit, idempotency, cache, queues, socket adapter.');
w('- Webhook: raw body capture; HMAC with RAZORPAY_WEBHOOK_SECRET; CSRF skipped.');
w('- Secrets via dotenv layered load + validateEnv; JWT length enforced in production.');
w('- IP block list from settings; securityAudit events.');
w('');
w('---');
w('');
w('## 19. Complete Error Handling Inventory');
w('');
w('### 19.1 Error Classes');
w('');
w('| Class | Typical Status |');
w('|-------|----------------|');
w('| AppError | custom + code |');
w('| PermissionError | 403 |');
w('| NotFoundError | 404 |');
w('| RateLimitError / PaymentError | named |');
w('');
w('### 19.2 Response Shape');
w('');
w('Success: `{ success: true, message, data }`');
w('');
w('Error:');
w('```json');
w('{');
w('  "success": false,');
w('  "message": "...",');
w('  "error": { "statusCode": 401, "timestamp": "...", "path": "...", "code": "INVALID_CREDENTIALS" },');
w('  "data": null');
w('}');
w('```');
w('');
w('### 19.3 Notable Codes');
w('');
w('`ACCOUNT_NOT_FOUND`, `INVALID_CREDENTIALS`, `SESSION_REPLACED`, `VALIDATION_ERROR`, `AUTH_ERROR`, `DATABASE_UNAVAILABLE`, `DUPLICATE_ENTRY`, `FILE_UPLOAD_ERROR`, `REQUEST_TIMEOUT`, permission denials.');
w('');
w('### 19.4 Global Handler');
w('');
w('Normalizes Mongoose/JWT/Multer/DB errors; hides 500 details in production; last middleware after notFound.');
w('');
w('---');
w('');
w('## 20. Complete Logging Inventory');
w('');
w('| System | Role |');
w('|--------|------|');
w('| Winston | Structured JSON; console; optional files error/combined/performance; LOG_LEVEL; correlation child loggers |');
w('| Morgan | HTTP access `dev` |');
w('| requestLogger | Extra method+URL console |');
w('| correlationMiddleware | Start/finish with duration |');
w('| monitoringMiddleware | Metrics + slow warnings |');
w('| securityAudit | Winston warn + Redis security:events |');
w('| Audit model | Mongo domain audit rows |');
w('| Sentry | Optional DSN; strips cookies/auth; sample rate prod |');
w('');
w('---');
w('');
w('## 21. Logistics, Credit & Supporting Modules');
w('');
w('### 21.1 Logistics Lifecycle');
w('');
w('```');
w('ASSIGNED -> ACCEPTED -> PICKED -> OUT_FOR_DELIVERY -> DELIVERED -> COMPLETED');
w('```');
w('');
w('Maps to order PROCESSING/PACKED/OUT_FOR_DELIVERY/DELIVERED/COMPLETED when rank increases.');
w('');
w('Admin createShipment + assign/reassign; partner location updates; analytics.');
w('');
w('### 21.2 Credit');
w('');
w('- Collection statuses ACTIVE/BLOCKED (constants PENDING/APPROVED/REJECTED unused by model).');
w('- Ledger DEBIT/CREDIT; maxCreditLimit setting; auto-create demo limit.');
w('- Admin also patches User.creditLimit/availableCredit — dual store.');
w('');
w('### 21.3 External Services Status');
w('');
w('| Service | Status |');
w('|---------|--------|');
w('| Razorpay | Production-capable when keys set |');
w('| Cloudinary | Env-gated |');
w('| S3 | Optional USE_S3_STORAGE |');
w('| Socket.io | Implemented; Redis adapter optional |');
w('| Sentry | Env-gated |');
w('| Email | Console mock |');
w('| SMS | Missing service file |');
w('');
w('---');
w('');
w('## 22. Known Implementation Limitations');
w('');
w('### 22.1 Critical / Certification Blockers');
w('');
w('1. **post-payment / post-order BullMQ workers are not started by `server.js`** — jobs may enqueue with no consumer; auto invoice/assign may not run.');
w('2. **Online stock is Redis soft-reservation only** — `Inventory.reservedStock` not hard-held; oversell risk if Redis down/TTL expires.');
w('3. **Payment reconcile restoreStock can inflate inventory** for online reserved (non-deducted) orders.');
w('4. **Bank-transfer approve sets PROCESSING**, bypassing workflow `PENDING_PAYMENT -> CONFIRMED`.');
w('5. **`JWT_REFRESH_SECRET` unused** — both tokens use `JWT_SECRET`.');
w('');
w('### 22.2 Functional Gaps');
w('');
w('6. Promotion `apply` API not integrated into `createOrder`.');
w('7. Pricing engine tiers differ from checkout bulk tiers.');
w('8. Dual Logistics vs Shipment modules; Order.shipmentId refs Logistics.');
w('9. Dual credit stores (Credit collection vs User fields).');
w('10. Email mock; SMS job broken.');
w('11. `USE_REAL_QUEUE=false` stubs many module queues.');
w('12. `health.routes.js` orphaned; logistics import in app.js unused.');
w('13. Bank transfer amount not enforced; bank details hardcoded in payment.config.');
w('14. Invoice GST accounting may disagree with createOrder +18% model.');
w('15. Global XSS escape can alter intentional special characters.');
w('16. CSRF cookie httpOnly requires body token for header (document for clients).');
w('17. cancelPendingOrders / credit limit schedulers not cron-wired.');
w('18. Delivery auto-assign may look for lowercase `active` status mismatching `ACTIVE`.');
w('19. Rejected bank proof does not release reservation.');
w('20. Cart has no quantity-update endpoint.');
w('');
w('---');
w('');
w('## 23. Backend Statistics');
w('');
w('Measured from `Production/b2b-backend/src` on **2026-07-27**.');
w('');
w('| Metric | Count |');
w('|--------|------:|');
w('| **Total APIs** (route method registrations approx.) | **~179** |');
w('| **Route files** (`*.routes.js`) | **33** |');
w('| **Controllers** (`*.controller.js`) | **31** |');
w('| **Services** (`*.service.js`) | **51** |');
w('| **Middlewares** (`src/middlewares`) | **23** |');
w('| **Models** (`*.model.js`) | **26** (+ CreditLedger = **28 collections**) |');
w('| **Repositories** | **25** |');
w('| **Validators** (`*.validation.js` / schemas) | **30** |');
w('| **Workers** (`src/workers`) | **3** |');
w('| **Jobs** (`src/jobs`) | **8** |');
w('| **Queue modules** (`src/queues`) | **6** |');
w('| **Utilities** (`src/utils`) | **24** |');
w('| **Config files** (`src/config` excl. mocks) | **17** |');
w('| **Domain modules** under `src/modules` | **~30** |');
w('| **Source JS files** | **~327** |');
w('| **Approximate Lines of Code (src)** | **~19,085** |');
w('');
w('### Redis Usage Summary');
w('');
w('Rate limiting, idempotency, payment/webhook locks, fraud counters, inventory reservations, HTTP cache, security events, BullMQ, optional Socket.io adapter.');
w('');
w('### BullMQ Queues Summary');
w('');
w('Real: `post-payment`, `post-order`, `notification`, `email`, plus stubs for inventory/payment/audit/webhook/image/archival. Module `USE_REAL_QUEUE=false` stubs many producers.');
w('');
w('### Feature Module Roll-Up');
w('');
w('1. Authentication & Sessions  ');
w('2. Users & Profile  ');
w('3. Catalog (Products/Categories/Search/Reviews/Pricing)  ');
w('4. Cart & Wishlist  ');
w('5. Orders & Workflow  ');
w('6. Payments (Razorpay/Hybrid/COD/Credit/Bank/Refunds)  ');
w('7. Invoices  ');
w('8. Credit & Ledger  ');
w('9. Inventory & Warehouses  ');
w('10. Logistics & Delivery  ');
w('11. Notifications  ');
w('12. Admin / Approvals / Super Admin  ');
w('13. Analytics & Audit  ');
w('14. Settings & Feature Flags  ');
w('15. Support Tickets  ');
w('16. Promotions / Companies / Vendors / Upload  ');
w('');
w('---');
w('');
w('## Appendix A — Order Status Enum');
w('');
w('`CREATED | PENDING_PAYMENT | PENDING | CONFIRMED | PROCESSING | PACKED | READY_TO_DISPATCH | SHIPPED | OUT_FOR_DELIVERY | DELIVERED | COMPLETED | CANCELLED | RETURNED | REFUNDED | FAILED`');
w('');
w('## Appendix B — Payment / Delivery Enums');
w('');
w('- Order paymentStatus: `PENDING | PAID | FAILED | REJECTED | REFUNDED`');
w('- Payment record: `INITIATED | PENDING | SUCCESS | FAILED`');
w('- PaymentProof: `PENDING | APPROVED | REJECTED`');
w('- Delivery: `PENDING | ASSIGNED | ACCEPTED | PICKED | OUT_FOR_DELIVERY | DELIVERED | COMPLETED | CANCELLED | FAILED`');
w('');
w('## Appendix C — Cookie & Header Names');
w('');
w('| Name | Use |');
w('|------|-----|');
w('| `Authorization: Bearer` | Access JWT |');
w('| Cookie `accessToken` | Access fallback |');
w('| Cookie/body `refreshToken` | Refresh |');
w('| Cookie `csrf-token` | CSRF (httpOnly) |');
w('| Header `x-csrf-token` | CSRF submit |');
w('| Header `idempotency-key` | Dedup |');
w('| `x-correlation-id` / `x-request-id` | Tracing |');
w('| `x-playwright-test` / `x-automated-test` | Bypass rate limits when =1 |');
w('| `x-razorpay-signature` | Webhook |');
w('');
w('---');
w('');
w('*End of BACKEND_DOCUMENTATION.md — Master Backend Implementation Reference.*');
w('');

fs.appendFileSync(out, L.join('\n'), 'utf8');
console.log('Part D final', fs.statSync(out).size);
