const fs = require('fs');
const path = require('path');
const out = path.join(__dirname, '..', 'BACKEND_DOCUMENTATION.md');
const L = [];
const w = (s = '') => L.push(s);

w('');
w('## 7. Complete Database Inventory');
w('');
w('**Driver:** Mongoose 9. **Collections:** 28 (27 `*.model.js` + CreditLedger). Soft delete: **User only** (`isDeleted` + find middleware).');
w('');
w('### 7.1 Connection');
w('');
w('- URI: `MONGO_URI_DIRECT` > `MONGO_URI` > in-memory when `USE_IN_MEMORY_MONGO`.');
w('- Pool 2-10; IPv4 first; env DB allowlist; Super Admin bootstrap after connect.');
w('- Transactions only when replica set detected (`getTransactionSupport()`).');
w('');
w('### 7.2 Collections Summary');
w('');
w('| # | Model | Collection | Key Fields / Notes | Unique / Special Indexes |');
w('|---|-------|------------|--------------------|--------------------------|');
w('| 1 | User | users | name, email, mobile, password(select:false), role, status, companyId, 2FA, creditLimit/availableCredit, vehicle*, addresses, activeSessionId, isDeleted | unique email, mobile; soft-delete filter |');
w('| 2 | Company | companies | name, email, phone, gstNumber, isActive, createdBy | unique email |');
w('| 3 | Vendor | vendors | name, companyId, contact, status PENDING/APPROVED/REJECTED | companyId index |');
w('| 4 | Product | products | name, price, stock, categoryId, vendorId, moq, gst, bulkPricing, variants, images, isActive | category/name indexes |');
w('| 5 | Category | categories | name, slug, parentId, image, isActive | unique {name, parentId} |');
w('| 6 | Order | orders | userId, items[], totalAmount, paymentMethod, paymentStatus, status, address, shipmentId, idempotencyKey, statusHistory, paymentAttempts | sparse unique idempotencyKey; compounds user/status/dates |');
w('| 7 | Cart | carts | userId, items[{productId, quantity}] | unique userId |');
w('| 8 | Payment | payments | orderId, userId, amount, status INITIATED/PENDING/SUCCESS/FAILED, method, razorpayPaymentId | sparse unique razorpayPaymentId |');
w('| 9 | Refund | refunds | orderId, paymentId, amount, FULL/PARTIAL, status, razorpayRefundId, inventoryRestored | sparse unique razorpayRefundId |');
w('| 10 | PaymentProof | paymentproofs | orderId, userId, amount, utrNumber, screenshot, PENDING/APPROVED/REJECTED | compounds order/status |');
w('| 11 | Invoice | invoices | orderId unique, invoiceNumber unique, amounts, gst, fileUrl | |');
w('| 12 | Inventory | inventories | productId, warehouseId, stock, reservedStock, reorderLevel, version | unique {productId, warehouseId} |');
w('| 13 | Warehouse | warehouses | name, location, capacity, currentLoad, isActive | |');
w('| 14 | Credit | credits | userId unique, creditLimit, usedCredit, availableCredit, ACTIVE/BLOCKED | pre-save available = limit - used |');
w('| 15 | CreditLedger | creditledgers | userId, DEBIT/CREDIT, amount, description | |');
w('| 16 | Logistics | logistics | orderId, warehouseId, deliveryPartnerId, DELIVERY_STATUS, trackingNumber unique, location, proof | |');
w('| 17 | Shipment | shipments | orderId, warehouseId, CREATED/IN_TRANSIT/DELIVERED, trackingNumber | **Legacy parallel module** |');
w('| 18 | Promotion | promotions | code unique, PERCENTAGE/FLAT, value, maxDiscount, expiresAt | |');
w('| 19 | Notification | notifications | userId, title, message, ORDER/PAYMENT/SYSTEM, isRead | |');
w('| 20 | Review | reviews | userId, productId, rating 1-5, comment | |');
w('| 21 | Wishlist | wishlists | userId unique, items[{productId}] | |');
w('| 22 | Audit | audits | userId, action, entity, details/data, severity | |');
w('| 23 | Support | supports | userId, subject, message, OPEN/IN_PROGRESS/RESOLVED/CLOSED | |');
w('| 24 | Settings | settings | key unique, value Mixed | platform flags |');
w('| 25 | UserSettings | usersettings | userId unique, notifications, preferences, businessDetails | |');
w('| 26 | PasswordResetToken | passwordresettokens | userId, tokenHash, expiresAt | **TTL** on expiresAt |');
w('| 27 | RefreshToken | refreshtokens | userId, token unique, family, expiresAt, device, revoke flags, reuseDetected | **TTL** expiresAt; family compounds |');
w('');
w('### 7.3 Relationships (refs)');
w('');
w('```');
w('User -> Company');
w('Product -> Category, User(vendor), Company');
w('Order -> User, Product(items), Logistics(shipmentId)');
w('Cart/Wishlist/Credit/Notification/Review/Support/UserSettings/PaymentProof/RefreshToken/PasswordResetToken -> User');
w('Payment/Refund/Invoice/Logistics/Shipment/PaymentProof -> Order');
w('Inventory/Logistics/Shipment -> Warehouse');
w('Refund -> Payment, Product(restoredItems)');
w('Vendor -> Company');
w('Category -> Category (parentId)');
w('```');
w('');
w('### 7.4 Transactions');
w('');
w('- **Order placement:** session transaction when replica set; create order + credit deduct / stock reduce (COD/CREDIT) or Redis reserve (online).');
w('- **Mark failed:** snapshot/majority transaction + restoreStock.');
w('- **Hybrid payment:** Redis lock + optional Mongo transaction.');
w('- Standalone Mongo: degrade to sequential writes / manual rollback.');
w('');
w('### 7.5 Seed / Migration Scripts');
w('');
w('| Script | Role |');
w('|--------|------|');
w('| `scripts/db/init-db.js` | createIndexes + baseline Settings (non-prod) |');
w('| `scripts/db/seed-qa.js` | Idempotent QA dataset |');
w('| `scripts/migration/preview.js` | Dry-run compare |');
w('| `dangerous-dev-tools/*` | Destructive seeds (gated) |');
w('| `scripts/migrate.js`, `scripts/seed.js` | Empty stubs |');
w('');
w('---');
w('');
w('## 8. Complete Module Inventory');
w('');
w('For each module: Purpose | APIs (summary) | AuthZ | Validation | Business rules | DB | Transactions | Errors | Jobs | Status');
w('');
w('### 8.1 auth');
w('**Purpose:** Register/login/2FA/refresh/logout/password/sessions/CSRF.  ');
w('**APIs:** See Section 4.2. **Auth:** Mixed public/protected. **Validation:** Joi schemas for register/login/reset/2FA/change-password.  ');
w('**Rules:** PENDING users cannot login (except SA); single activeSessionId; refresh family reuse detection; AUTH_STRICT_MODE gates.  ');
w('**DB:** User, RefreshToken, PasswordResetToken, Credit (default on register). **Status:** Implemented.');
w('');
w('### 8.2 user');
w('**Purpose:** Profile, photo, admin user CRUD. **APIs:** `/users/*`. **AuthZ:** self vs ADMIN/SA permissions. **DB:** User. **Status:** Implemented.');
w('');
w('### 8.3 product / category / pricing / search / review');
w('**Purpose:** Catalog. **APIs:** public read; admin/vendor write. **Rules:** MOQ; price>0; ownership; in-memory product list cache 5m; pricing engine separate from checkout bulk tiers; reviews one-per-user-product; search Mongo limit 20. **Status:** Implemented (promotions/pricing engine not on checkout).');
w('');
w('### 8.4 cart / wishlist');
w('**Purpose:** Per-user cart/wishlist. **Rules:** MOQ/stock check on add; prune stale products; cleared after successful pay/COD/credit/bank approve. **Status:** Implemented.');
w('');
w('### 8.5 order');
w('**Purpose:** Create orders, workflow status, fail, invoice download. **Rules:** See Section 12. **Idempotency:** key + limiter. **DB:** Order. **Tx:** Yes when replica set. **Status:** Implemented.');
w('');
w('### 8.6 payment / payment-proof / refund');
w('**Purpose:** Razorpay, hybrid, webhook, bank proofs, refunds. **Rules:** See Section 11. **External:** Razorpay. **Status:** Implemented (bank amount policy weak).');
w('');
w('### 8.7 invoice');
w('**Purpose:** Generate/list invoices; PDF via pdfkit under `/uploads/invoices`. **Status:** Implemented (GST accounting may disagree with createOrder).');
w('');
w('### 8.8 credit');
w('**Purpose:** Credit accounts + ledger. **Rules:** ACTIVE/BLOCKED; maxCreditLimit; auto-create INR 50000 demo; dual User.credit* fields also updated by admin. **Status:** Partial (dual sources).');
w('');
w('### 8.9 inventory / warehouse');
w('**Purpose:** Multi-warehouse stock; optimistic version locking; default warehouse auto-create. **Rules:** checkStock across warehouses; no auto-seed missing rows on order. **Status:** Implemented.');
w('');
w('### 8.10 logistics / shipment');
w('**Purpose:** Delivery lifecycle (primary Logistics) + legacy Shipment module. **Rules:** Linear DP transitions; order status sync by rank; earnings ~5% in analytics. **Status:** Logistics implemented; Shipment legacy dual system.');
w('');
w('### 8.11 notification');
w('**Purpose:** Persist + queue + socket emit. **Email/SMS:** console mock / broken SMS import. **Status:** Partial.');
w('');
w('### 8.12 admin / adminApprovals / superAdmin');
w('**Purpose:** User governance, stats, SA config/audit/categories. **Status:** Implemented.');
w('');
w('### 8.13 analytics / audit / settings / support / promotion / company / vendor / upload');
w('**Purpose:** As named. **Notes:** Promotion apply not on checkout; Support no SLA; Upload Cloudinary/S3/local; Settings public config + platform keys. **Status:** Mostly implemented with noted gaps.');
w('');
w('---');
w('');
w('## 9. Complete Validation Inventory');
w('');
w('| Area | Mechanism | Key Rules |');
w('|------|-----------|-----------|');
w('| All validated routes | `validate.middleware` + Joi | FormData coercion; 400 messages |');
w('| Register | registerSchema | name, email, password policy, mobile, optional role |');
w('| Login | loginSchema | mobile/identifier + password |');
w('| Password | AUTH_STRICT_MODE | Strict: longer/complex (+ optional HIBP/history); non-strict min 6 |');
w('| Orders | createOrderSchema | paymentMethod, shippingAddress |');
w('| Order status | updateOrderStatusSchema + workflow | Allowed transitions only |');
w('| Payments | verify/hybrid schemas | Razorpay fields; amounts |');
w('| Bank proof | upload schema + multer | UTR; screenshot jpg/png/pdf <=5MB |');
w('| Products/Categories | create/update schemas | Required fields; price>0 |');
w('| Cart/Wishlist | add schemas | productId, quantity |');
w('| Credit | create/use/repay schemas | amounts |');
w('| Uploads | MIME + magic bytes + sanitize | jpeg/png/webp (+docs for general); 10MB; <=5 files |');
w('| Mongo sanitize | middleware | Strip `$` and `.` keys |');
w('| XSS sanitize | middleware | validator.escape strings |');
w('| Idempotency key | header | `[a-zA-Z0-9_-]{1,255}` |');
w('');
w('---');
w('');
w('## 10. Complete Business Rule Inventory');
w('');
w('1. New registrations default `PENDING` until Admin/SA approval (SUPER_ADMIN exempt).');
w('2. Single active session per user via `activeSessionId`.');
w('3. Refresh token family reuse revokes entire family.');
w('4. Maintenance mode blocks non-SUPER_ADMIN login and can block order create.');
w('5. Order cutoff time setting can 403 new orders.');
w('6. COD gated by `enableCOD`; credit gated by `creditSystem`.');
w('7. Checkout bulk discounts: qty tiers 5/10/15/20% then +18% GST.');
w('8. COD -> CONFIRMED + PENDING payment + immediate stock reduce.');
w('9. CREDIT -> CONFIRMED + PAID + stock reduce + credit deduct.');
w('10. Online/bank -> PENDING_PAYMENT + Redis reservation 15 minutes.');
w('11. Order status transitions enforced by workflow graph (Section 12).');
w('12. Payment verify/webhook require HMAC; amount mismatch fails order.');
w('13. Hybrid payment uses Redis lock; credit reverse on Razorpay failure.');
w('14. Bank transfer: no exact amount enforcement; approve sets PROCESSING (bypasses PENDING_PAYMENT->CONFIRMED).');
w('15. Refunds: PAID only; full refund restores stock + REFUNDED/CANCELLED.');
w('16. Inventory optimistic lock with retries; restoreStock targets first warehouse.');
w('17. Product list in-memory cache 5 minutes for default query.');
w('18. Vendor product mutations ownership-enforced.');
w('19. Soft quotas on products/orders/cart by role.');
w('20. Notifications respect global notifications setting.');
w('21. Logistics linear lifecycle; order status synced by rank when higher.');
w('22. Fraud: login/OTP/registration/payment velocity (strict mode).');
w('');
w('---');
w('');
w('## 11. Complete Payment Flow');
w('');
w('### 11.1 Methods Supported');
w('');
w('`COD | ONLINE | CREDIT | RAZORPAY | UPI | CARD | HYBRID | BANK_TRANSFER`');
w('');
w('### 11.2 Razorpay Path');
w('');
w('1. `create-order` / `initiate` / `hybrid` creates gateway order (min INR 1).');
w('2. Client verifies via `verify` with signature HMAC-SHA256.');
w('3. Replay protection Redis `payment:processed:{paymentId}` 24h.');
w('4. Lock `payment:lock:{orderId}` 60s.');
w('5. On success: order PAID + CONFIRMED; finalize reservation; clear cart; socket `payment:success`; `queuePostPaymentJobs`.');
w('6. Webhook `payment.captured`: raw body + `RAZORPAY_WEBHOOK_SECRET`; same success path; CSRF skipped.');
w('');
w('### 11.3 Hybrid');
w('');
w('- Optional credit debit then Razorpay for remainder.');
w('- Full credit cover: PAID without gateway.');
w('- COD branch inside hybrid: CONFIRMED + PENDING pay.');
w('- Razorpay failure reverses credit with idempotent key.');
w('');
w('### 11.4 Bank Transfer');
w('');
w('1. Vendor uploads UTR + screenshot while PENDING_PAYMENT.');
w('2. SUPER_ADMIN approves/rejects.');
w('3. Approve: PAID + **PROCESSING**; finalize reservation; clear cart.');
w('4. Reject: paymentStatus REJECTED; reservation **not** released.');
w('5. Amount policy: exact match **not enforced**.');
w('');
w('### 11.5 Refunds');
w('');
w('- Admin or owner; Redis idempotency; Razorpay refund; FULL restores inventory.');
w('');
w('### 11.6 Fail / Reconcile');
w('');
w('- `failPayment` / mark failed: FAILED + release reservation; COD restores stock.');
w('- Cron: PENDING/INITIATED payments >15m -> FAILED + restoreStock (**risk:** may inflate stock for reserved-only online orders).');
w('');
w('---');
w('');
w('## 12. Complete Order Flow');
w('');
w('### 12.1 Create');
w('');
w('Gates: address required; maintenance; cutoff; COD/credit flags; idempotencyKey.');
w('');
w('Pricing: MOQ check; bulk % tiers; GST 18%; commission from settings; heavy vehicle if weight >100.');
w('');
w('| Method | Order Status | Payment Status | Stock |');
w('|--------|--------------|----------------|-------|');
w('| COD | CONFIRMED | PENDING | Immediate reduce |');
w('| CREDIT | CONFIRMED | PAID | Immediate reduce + debit |');
w('| Online/Bank/etc. | PENDING_PAYMENT | PENDING | Redis reserve 900s |');
w('');
w('Post COD/CREDIT: clear cart, invoice, notify, queuePostOrderJobs.');
w('');
w('### 12.2 Status Workflow');
w('');
w('```');
w('CREATED -> PENDING_PAYMENT | PENDING | CONFIRMED | FAILED | CANCELLED');
w('PENDING_PAYMENT -> CONFIRMED | FAILED | CANCELLED');
w('PENDING -> CONFIRMED | CANCELLED | FAILED');
w('CONFIRMED -> PROCESSING | PACKED | CANCELLED');
w('PROCESSING -> PACKED | CANCELLED');
w('PACKED -> READY_TO_DISPATCH | CANCELLED');
w('READY_TO_DISPATCH -> SHIPPED | CANCELLED');
w('SHIPPED -> OUT_FOR_DELIVERY | CANCELLED');
w('OUT_FOR_DELIVERY -> DELIVERED | CANCELLED');
w('DELIVERED -> COMPLETED | RETURNED');
w('COMPLETED -> RETURNED');
w('RETURNED -> REFUNDED');
w('CANCELLED | FAILED | REFUNDED -> terminal');
w('```');
w('');
w('Admin `PATCH /orders/:id/status` validates transitions + statusHistory + audit.');
w('');
w('### 12.3 Fail');
w('');
w('`markOrderAsFailed` / payment fail: FAILED statuses; restoreStock when applicable.');
w('');
w('---');
w('');
w('## 13. Complete Cart Flow');
w('');
w('1. `POST /cart` auth: product active, MOQ, stock for merged qty.');
w('2. `GET /cart` prunes missing products.');
w('3. `DELETE /cart/:productId` removes line.');
w('4. Cleared on COD/CREDIT success, payment verify/webhook success, bank-transfer approve.');
w('5. No quantity-update endpoint (remove + re-add only).');
w('');
w('---');
w('');
w('## 14. Complete Product Flow');
w('');
w('1. Public list/detail/search.');
w('2. Create: ADMIN/SA/VENDOR + permission; image upload; ensureProductInventory; invalidate cache.');
w('3. Update/delete/stock: ownership or elevated permission.');
w('4. Status patch: ADMIN/SA only.');
w('5. Pricing API: optional dynamicPricing engine (qty 50/100 tiers) — **not** same as checkout bulk.');
w('6. Categories: public read; ADMIN/SA write with cache clear.');
w('');
w('---');
w('');
w('## 15. Complete Notification Flow');
w('');
w('1. Service checks notifications setting.');
w('2. Enqueue BullMQ `notification` queue + persist Notification document.');
w('3. Worker (when started): Socket.io `io.to(userId).emit("notification", ...)`.');
w('4. Templates: ORDER_PLACED, PAYMENT_SUCCESS, LOW_CREDIT.');
w('5. Email service: console mock. SMS job references missing `sms.service` — **broken**.');
w('6. Module-level queue stubs when `USE_REAL_QUEUE=false`.');
w('');
w('---');
w('');

fs.appendFileSync(out, L.join('\n'), 'utf8');
console.log('Part C', fs.statSync(out).size);
