const fs = require('fs');
const path = require('path');
const out = path.join(__dirname, '..', 'BACKEND_DOCUMENTATION.md');
const L = [];
const w = (s = '') => L.push(s);

w('# BACKEND IMPLEMENTATION DOCUMENTATION');
w('## Mokshith B2B Platform — Master Reference for Enterprise QA, Security Review & Production Certification');
w('');
w('| Field | Value |');
w('|-------|-------|');
w('| **Document Type** | Complete Backend Implementation Reference |');
w('| **Project** | `b2b-backend` (`Production/b2b-backend`) |');
w('| **Package Version** | 1.0.0 |');
w('| **Runtime** | Node.js >= 20 (ES Modules) |');
w('| **Stack** | Express 5 + Mongoose 9 + Redis (ioredis) + BullMQ + Socket.io + Joi + Winston + Razorpay |');
w('| **Architecture** | Modular monolith (`src/modules/*`) with shared middlewares, queues, workers, and services |');
w('| **API Base** | `/api/v1` (also aliased at `/api`) |');
w('| **Document Generated** | 2026-07-27 |');
w('| **Methodology** | Exhaustive source read of routes, controllers, services, models, middlewares, queues, workers, jobs, config |');
w('');
w('> This document describes **what is currently implemented** in the backend. It is the master reference for enterprise testing, security review, production certification, and maintenance.');
w('');
w('---');
w('');
w('## Table of Contents');
w('');
w('1. [System Overview](#1-system-overview)');
w('2. [Technology & Configuration Inventory](#2-technology--configuration-inventory)');
w('3. [Application Bootstrap & Middleware Stack](#3-application-bootstrap--middleware-stack)');
w('4. [Complete API Inventory](#4-complete-api-inventory)');
w('5. [Complete Authentication Flow](#5-complete-authentication-flow)');
w('6. [Complete Authorization Matrix](#6-complete-authorization-matrix)');
w('7. [Complete Database Inventory](#7-complete-database-inventory)');
w('8. [Complete Module Inventory](#8-complete-module-inventory)');
w('9. [Complete Validation Inventory](#9-complete-validation-inventory)');
w('10. [Complete Business Rule Inventory](#10-complete-business-rule-inventory)');
w('11. [Complete Payment Flow](#11-complete-payment-flow)');
w('12. [Complete Order Flow](#12-complete-order-flow)');
w('13. [Complete Cart Flow](#13-complete-cart-flow)');
w('14. [Complete Product Flow](#14-complete-product-flow)');
w('15. [Complete Notification Flow](#15-complete-notification-flow)');
w('16. [Complete Background Job Inventory](#16-complete-background-job-inventory)');
w('17. [Complete Cache Inventory](#17-complete-cache-inventory)');
w('18. [Complete Security Inventory](#18-complete-security-inventory)');
w('19. [Complete Error Handling Inventory](#19-complete-error-handling-inventory)');
w('20. [Complete Logging Inventory](#20-complete-logging-inventory)');
w('21. [Logistics, Credit & Supporting Modules](#21-logistics-credit--supporting-modules)');
w('22. [Known Implementation Limitations](#22-known-implementation-limitations)');
w('23. [Backend Statistics](#23-backend-statistics)');
w('');
w('---');
w('');
w('## 1. System Overview');
w('');
w('### 1.1 Product Purpose');
w('');
w('Backend for Mokshith B2B wholesale commerce. Serves four primary actor types via JWT-authenticated REST APIs, plus public catalog/search and a Razorpay webhook.');
w('');
w('| Role | Backend Enum | Primary Capabilities |');
w('|------|--------------|----------------------|');
w('| Super Admin | `SUPER_ADMIN` | Platform governance, admin CRUD, analytics/revenue, bank-proof approval, audit, config |');
w('| Admin | `ADMIN` | Catalog/inventory, vendor/user approvals, order workflow, delivery assignment, ops stats |');
w('| Vendor / B2B Customer | `VENDOR` / `B2B_CUSTOMER` | Browse, cart, checkout, credit, invoices, wishlist, bank-transfer proofs |');
w('| Delivery Partner | `DELIVERY_PARTNER` | Accept/pick/start/deliver/complete shipments, location updates |');
w('| B2C Customer | `B2C_CUSTOMER` | Similar to B2B minus credit (role exists in permissions matrix) |');
w('');
w('### 1.2 Architectural Style');
w('');
w('- **Modular monolith**: each domain under `src/modules/<name>/` typically contains routes, controller, service, model, validation, repository.');
w('- **Entry**: `server.js` loads env, connects Mongo + Redis, creates HTTP + Socket.io, starts cron/workers when gated.');
w('- **App factory**: `src/app.js` wires global middleware and mounts `/api`.');
w('- **Dual mount**: v1 routes at `/api/v1` and `/api` for backward compatibility.');
w('- **Realtime**: Socket.io rooms by `userId`; optional Redis adapter.');
w('- **Async work**: BullMQ queues + node-cron; many workers stubbed or orphaned (see Section 16).');
w('');
w('### 1.3 Source Tree');
w('');
w('```');
w('Production/b2b-backend/');
w('|- server.js');
w('|- scripts/ (db init, QA seed, migration preview, auth utilities)');
w('|- dangerous-dev-tools/ (destructive seeds — gated)');
w('`- src/');
w('   |- app.js, bootstrap/');
w('   |- config/');
w('   |- constants/');
w('   |- middlewares/ (23 files)');
w('   |- modules/ (auth, user, product, order, payment, logistics, ...)');
w('   |- models/ (RefreshToken, PasswordResetToken)');
w('   |- routes/ (v1, v2; orphan health.routes.js)');
w('   |- services/, queues/, workers/, jobs/');
w('   |- utils/, validations/, errors/');
w('   `- uploads/invoices/');
w('```');
w('');
w('---');
w('');
w('## 2. Technology & Configuration Inventory');
w('');
w('### 2.1 Runtime Dependencies (selected)');
w('');
w('| Package | Role |');
w('|---------|------|');
w('| express ^5.2 | HTTP framework |');
w('| mongoose ^9.6 | MongoDB ODM |');
w('| ioredis / redis | Cache, locks, rate limit, queues |');
w('| bullmq ^5.41 | Job queues |');
w('| jsonwebtoken / bcryptjs | Auth |');
w('| joi / validator | Validation / XSS escape |');
w('| helmet / cors / compression / cookie-parser | Security & HTTP |');
w('| express-rate-limit | Rate limiting |');
w('| razorpay | Payments |');
w('| cloudinary / @aws-sdk/client-s3 | Uploads |');
w('| socket.io / @socket.io/redis-adapter | Realtime |');
w('| winston / morgan / @sentry/node | Logging & APM |');
w('| multer / pdfkit / qrcode / @otplib | Uploads, invoices, 2FA |');
w('| node-cron | Scheduled jobs |');
w('');
w('### 2.2 Environment Variables');
w('');
w('| Variable | Required | Purpose |');
w('|----------|----------|---------|');
w('| `NODE_ENV` | Yes | development / qa / uat / production / test |');
w('| `PORT` | No (5000) | HTTP port |');
w('| `FRONTEND_URL` | Recommended | CORS + password-reset links |');
w('| `MONGO_URI` / `MONGO_URI_DIRECT` | Yes | Mongo connection |');
w('| `APP_DATABASE_NAME` | Env-gated | Expected DB name per environment |');
w('| `USE_IN_MEMORY_MONGO` | Dev | Embedded Mongo for local |');
w('| `JWT_SECRET` | Yes (>=64 chars prod) | Access + refresh JWT signing |');
w('| `JWT_REFRESH_SECRET` | Validated | Present in env validation but **unused by token signer** |');
w('| `JWT_EXPIRES_IN` | No (15m) | Access TTL |');
w('| `JWT_REFRESH_EXPIRES_IN` | No (7d) | Refresh TTL |');
w('| `AUTH_STRICT_MODE` | No (default true) | Password/fraud/rate-limit strictness |');
w('| `RAZORPAY_KEY_ID/SECRET/WEBHOOK_SECRET` | Online pay | Gateway |');
w('| `REDIS_*` / `REDIS_URL` | Recommended | Redis |');
w('| `USE_SOCKET_REDIS_ADAPTER` | No | Socket horizontal scale |');
w('| `CLOUDINARY_*` | Recommended | Image CDN |');
w('| `USE_S3_STORAGE` + `S3_*` | Optional | Object storage |');
w('| `SMTP_*` | Optional | Email (currently console mock) |');
w('| `SENTRY_DSN` | Optional | Error tracking |');
w('| `ENABLE_CRON` / `ENABLE_WORKERS` | Optional | Background processing gates |');
w('| `LOG_LEVEL` | Optional | Winston level |');
w('| `ENFORCE_CSRF_IN_TESTS` | Test | Force CSRF in test env |');
w('');
w('### 2.3 Environment Database Policy');
w('');
w('| NODE_ENV | Expected DB |');
w('|----------|-------------|');
w('| development | `mokshith-dev` |');
w('| qa | `mokshith-qa` |');
w('| uat | `mokshith-uat` |');
w('| production | `mokshith-production` |');
w('| test | `mokshith-test` |');
w('');
w('Connect options: pool 2-10, serverSelectionTimeout 10s, socketTimeout 45s, IPv4 first. Production blocks `dropDatabase` / collection drop.');
w('');
w('---');
w('');
w('## 3. Application Bootstrap & Middleware Stack');
w('');
w('### 3.1 Startup Sequence (`server.js`)');
w('');
w('1. `loadEnv()` then `validateEnv()`');
w('2. `initializeSentry(app)`');
w('3. `setupQueryTimeout()`');
w('4. `connectDB()` (+ Super Admin bootstrap)');
w('5. `redisClient.connect()`');
w('6. HTTP server + Socket.io');
w('7. Optional Redis socket adapter; `global.io`');
w('8. Listen on `PORT`');
w('9. Conditionally `startCronJobs` / `startWorkers`');
w('10. Graceful shutdown handlers');
w('');
w('### 3.2 Global Middleware Order');
w('');
w('| # | Middleware | Behavior |');
w('|---|------------|----------|');
w('| 1 | Upload CORS + static `/uploads` | Serve files |');
w('| 2 | Health mounts | `/health`, `/api/health`, `/api/v1/health` (+ live/ready/redis) |');
w('| 3 | `trust proxy = 1` | Correct client IP |');
w('| 4 | Sentry request/tracing | Shim/passthrough in current setup |');
w('| 5 | `correlationMiddleware` | `x-correlation-id` / `x-request-id` |');
w('| 6 | monitoring + errorRateTracker | Duration, slow >3s |');
w('| 7 | compression | Skip if `x-no-compression` |');
w('| 8 | corsConfig | Allowlist + credentials |');
w('| 9 | ipBlockMiddleware | Setting `blockedIps` |');
w('| 10 | timeoutMiddleware(30000) | 408 after 30s |');
w('| 11 | Helmet + mongoSanitize + xssSanitize + apiLimiter | Security |');
w('| 12 | cookieParser | Cookies |');
w('| 13 | express.json 10mb (rawBody for webhook) | Body parse |');
w('| 14 | morgan + requestLogger | Access logs |');
w('| 15 | idempotencyMiddleware | Header-gated Redis dedupe |');
w('| 16 | `/metrics` | Monitoring |');
w('| 17 | `/api` routes | v1/v2 |');
w('| 18 | notFound | 404 JSON |');
w('| 19 | Sentry error handler | Passthrough |');
w('| 20 | errorHandler | Normalized JSON errors |');
w('');
w('### 3.3 API Mounting');
w('');
w('```');
w('/api/v1/*  -> v1.routes.js (primary)');
w('/api/*     -> v1.routes.js (alias)');
w('/api/v2/*  -> v2.routes.js (placeholder)');
w('```');
w('');
w('`src/routes/health.routes.js` exists but is **not mounted** (orphaned).');
w('');
w('---');
w('');

fs.writeFileSync(out, L.join('\n'), 'utf8');
console.log('Part A written', fs.statSync(out).size);
