const fs = require('fs');
const path = require('path');
const out = path.join(__dirname, '..', 'BACKEND_DOCUMENTATION.md');
const L = [];
const w = (s = '') => L.push(s);

w('');
w('## 4. Complete API Inventory');
w('');
w('All v1 paths are available under **both** `/api/v1/...` and `/api/...`. Tables show canonical `/api/v1` paths.');
w('');
w('### 4.1 Health / Metrics / Static / v2');
w('');
w('| METHOD | Path | Auth | Purpose |');
w('|--------|------|------|---------|');
w('| GET | `/health`, `/api/health`, `/api/v1/health` | No | Full health |');
w('| GET | `*/health/live` | No | Liveness |');
w('| GET | `*/health/ready` | No | Readiness (DB + Redis) |');
w('| GET | `/api/v1/health/redis` | No | Redis-only |');
w('| GET | `/metrics` | No | Monitoring metrics |');
w('| GET | `/uploads/:filename`, `/uploads/:folder/:filename` | No | Serve uploads |');
w('| GET | `/api/v2/`, `/api/v2/health` | No | v2 placeholders |');
w('');
w('### 4.2 Auth — `/api/v1/auth` (requireDatabase)');
w('');
w('| METHOD | Path | Auth | CSRF | Extra | Purpose |');
w('|--------|------|------|------|-------|---------|');
w('| POST | `/auth/register` | No | Issues token | authLimiter, registrations flag, Joi | Register PENDING |');
w('| POST | `/auth/login` | No | Issues token | authLimiter, Joi | Login or 2FA challenge |');
w('| POST | `/auth/forgot-password` | No | No | authLimiter | Reset request |');
w('| POST | `/auth/reset-password` | No | No | authLimiter | Reset with token |');
w('| POST | `/auth/refresh-token` | No | No | — | Rotate tokens |');
w('| GET | `/auth/csrf-token` | No | No | — | Issue CSRF |');
w('| POST | `/auth/logout` | No | No | — | Revoke refresh |');
w('| POST | `/auth/2fa/verify` | No | No | authLimiter | Complete 2FA login |');
w('| POST | `/auth/2fa/enable` | Yes | Yes | — | Start TOTP setup |');
w('| POST | `/auth/2fa/verify-setup` | Yes | Yes | Joi | Confirm 2FA |');
w('| POST | `/auth/2fa/disable` | Yes | Yes | — | Disable 2FA |');
w('| POST | `/auth/change-password` | Yes | Yes | Joi | Change password |');
w('| POST | `/auth/logout-all` | Yes | Yes | — | Revoke all sessions |');
w('| GET | `/auth/sessions` | Yes | No | — | List sessions |');
w('| DELETE | `/auth/sessions/:tokenId` | Yes | Yes | — | Revoke one |');
w('');
w('### 4.3 Users — parent Auth + injectCsrf');
w('');
w('| METHOD | Path | AuthZ | Purpose |');
w('|--------|------|-------|---------|');
w('| GET | `/users/me` | Auth | Profile |');
w('| PUT | `/users/me` | Auth+CSRF+Joi | Update profile |');
w('| POST | `/users/profile-image` | Auth+CSRF+upload | Profile image |');
w('| PUT | `/users/change-password` | Auth+CSRF | Change password |');
w('| GET | `/users/sessions` | Auth | Sessions |');
w('| POST | `/users/logout-all` | Auth+CSRF | Logout all |');
w('| GET | `/users/` | ADMIN/SA + USERS_LIST | List users |');
w('| GET | `/users/:id` | ADMIN/SA + USERS_READ | Get user |');
w('| DELETE | `/users/:id` | SUPER_ADMIN + USERS_DELETE | Delete user |');
w('');
w('### 4.4 Catalog — Categories / Products / Pricing / Search / Reviews');
w('');
w('| METHOD | Path | AuthZ | Purpose |');
w('|--------|------|-------|---------|');
w('| GET | `/categories`, `/categories/:id` | Public | List/detail |');
w('| POST/PUT/DELETE | `/categories`... | ADMIN/SA + CSRF (+ upload) | CRUD |');
w('| GET | `/products`, `/products/:id` | Public | List/detail |');
w('| POST | `/products` | ADMIN/SA/VENDOR + PRODUCTS_CREATE + CSRF + upload | Create |');
w('| PUT/DELETE | `/products/:id` | OwnershipOr permission + CSRF | Update/delete |');
w('| PATCH | `/products/:id/stock` | Ownership + INVENTORY_UPDATE | Stock |');
w('| PATCH | `/products/:id/status` | ADMIN/SA | Status |');
w('| POST | `/pricing` | Public + Joi | Calculate price |');
w('| GET | `/search` | Public | Product search |');
w('| POST | `/reviews` | Auth + feature flag | Add review |');
w('| GET | `/reviews/:productId` | Public | List reviews |');
w('');
w('### 4.5 Commerce — Cart / Wishlist / Orders / Invoices / Credit / Promotions');
w('');
w('| METHOD | Path | AuthZ | Purpose |');
w('|--------|------|-------|---------|');
w('| GET/POST | `/cart` | Auth | Get / add |');
w('| DELETE | `/cart/:productId` | Auth | Remove |');
w('| GET | `/wishlist` | Auth | Get |');
w('| POST | `/wishlist/add` | Auth+Joi | Add |');
w('| DELETE | `/wishlist/remove/:productId`, `/wishlist/clear` | Auth | Remove/clear |');
w('| POST | `/orders` | Auth+CSRF+orderLimiter+Idem+Joi | Create order |');
w('| GET | `/orders`, `/orders/:id` | Auth | List/detail |');
w('| GET | `/orders/:id/invoice` | Auth | Invoice PDF |');
w('| PATCH | `/orders/:id/status` | ADMIN/SA+CSRF+Joi | Status workflow |');
w('| POST | `/orders/:id/fail` | Auth+CSRF | Mark failed |');
w('| GET | `/invoices`, `/invoices/:orderId` | Auth | List/get |');
w('| POST | `/invoices/:orderId` | Auth+Joi | Generate |');
w('| GET | `/credit`, `/credit/ledger` | Auth | Balance/ledger |');
w('| POST | `/credit` | ADMIN/SA | Create credit account |');
w('| POST | `/credit/use`, `/credit/repay` | Auth+Joi | Use/repay |');
w('| CRUD | `/promotions` | ADMIN | Promo management |');
w('| POST | `/promotions/apply` | Auth+Joi | Apply coupon (**not wired into createOrder**) |');
w('');
w('### 4.6 Payments');
w('');
w('| METHOD | Path | AuthZ | Purpose |');
w('|--------|------|-------|---------|');
w('| POST | `/payments/webhook` | Public + paymentLimiter | Razorpay webhook |');
w('| POST | `/payments/create-order` | Auth+CSRF+RL | Razorpay order |');
w('| POST | `/payments/initiate/:orderId` | Auth+CSRF+RL | Initiate |');
w('| POST | `/payments/verify` | Auth+CSRF+RL+Joi | Verify signature |');
w('| POST | `/payments/fail` | Auth+CSRF+RL | Fail |');
w('| POST | `/payments/hybrid` | Auth+CSRF+RL+Joi | Hybrid/COD/credit |');
w('| POST | `/payments/refund` | Auth+CSRF+RL | Refund |');
w('| GET | `/payments/refund/...` | Auth | Refund queries |');
w('| GET | `/payments/bank-transfer/bank-details` | Auth | Bank details |');
w('| POST | `/payments/bank-transfer/upload` | Auth+CSRF+multer+Joi | Upload proof |');
w('| GET | `/payments/bank-transfer/pending` | SUPER_ADMIN | Pending proofs |');
w('| GET | `/payments/bank-transfer/order/:orderId` | Auth | Proof by order |');
w('| PATCH | `/payments/bank-transfer/:id/approve` | SUPER_ADMIN+CSRF | Approve |');
w('| PATCH | `/payments/bank-transfer/:id/reject` | SUPER_ADMIN+CSRF | Reject |');
w('');
w('### 4.7 Logistics / Shipments / Warehouses / Inventory');
w('');
w('| METHOD | Path | Roles | Purpose |');
w('|--------|------|-------|---------|');
w('| GET | `/logistics/delivery-queue`, `/history`, `/analytics` | ADMIN/DP/SA | Ops views |');
w('| GET | `/logistics/my-assignments` | DELIVERY_PARTNER | Assignments |');
w('| POST | `/logistics/:id/accept|pick|start|delivered|complete|location` | DELIVERY_PARTNER | Lifecycle |');
w('| POST | `/logistics/:orderId` | ADMIN/SA | Create shipment |');
w('| PATCH | `/logistics/:id/assign|reassign` | ADMIN/SA+Joi | Assign partner |');
w('| GET | `/logistics/:id`, `/logistics/` | Auth / ADMIN/SA | Details/list |');
w('| CRUD-ish | `/shipments` | ADMIN (+ DP status) | Legacy shipment module |');
w('| CRUD | `/warehouses` | ADMIN write | Warehouses |');
w('| GET/POST/PATCH | `/inventory`... | ADMIN (+ VENDOR update) + Idem | Stock ops |');
w('');
w('### 4.8 Admin / Super Admin / Analytics / Audit / Settings / Support / Upload / Companies / Vendors / Notifications');
w('');
w('| Area | Key Endpoints | Roles |');
w('|------|---------------|-------|');
w('| Admin | `/admin/users`, `/admin/stats`, approve/reject, create B2B/DP, update status/credit | ADMIN/SA |');
w('| Admin Approvals | `/admin-approvals`, pending, approve/reject | SUPER_ADMIN |');
w('| Super Admin | `/super-admin` and `/superadmin` users/admins/stats/metrics/audit-logs/config/categories | SUPER_ADMIN |');
w('| Analytics | `/analytics/dashboard|sales|...|revenue` SUPER_ADMIN; `/analytics/delivery` ADMIN/SA | As noted |');
w('| Audit | `/audit`, `/audit/:id` | ADMIN/SA |');
w('| Settings | `/settings`, `/settings/public/config`, `/settings/platform` | Mixed |');
w('| Support | `/support`, my-tickets, all, status | Auth; admin for all |');
w('| Upload | `/upload/image` | Auth+CSRF+cloud |');
w('| Companies | CRUD + `/companies/me` | Auth; ADMIN/SA create |');
w('| Vendors | create/list; PATCH status | Auth; ADMIN/SA approve |');
w('| Notifications | GET; mark read / read-all | Auth |');
w('');
w('**Approximate distinct v1 route method registrations:** ~179.');
w('');
w('---');
w('');
w('## 5. Complete Authentication Flow');
w('');
w('### 5.1 Token Model');
w('');
w('| Token | TTL | Secret | Payload | Client Storage |');
w('|-------|-----|--------|---------|----------------|');
w('| Access JWT | 15m | `JWT_SECRET` | `{ id, role, sessionId? }` | `Authorization: Bearer` or cookie `accessToken` |');
w('| Refresh | 7d DB | Signed with `JWT_SECRET` + random suffix; stored in RefreshToken | Family rotation | Body / cookie `refreshToken` |');
w('| CSRF | 24h cookie | 32-byte hex | N/A | Cookie `csrf-token` (httpOnly) + header `x-csrf-token` from response body |');
w('| Password reset | 1h | SHA-256 hash | N/A | Email link |');
w('');
w('**Note:** `JWT_REFRESH_SECRET` is env-validated but **not used** by the token signer.');
w('');
w('### 5.2 Register');
w('');
w('1. Rate limit + `allowRegistration` setting + Joi.');
w('2. Fraud track registration IP/email.');
w('3. Unique email/mobile; password policy (`AUTH_STRICT_MODE`).');
w('4. Create user `PENDING`, default credit account (INR 50000), audit REGISTER.');
w('5. Return user + csrfToken — **no access/refresh tokens**.');
w('');
w('### 5.3 Login');
w('');
w('1. Identifier = email or 10-digit mobile + password.');
w('2. Fraud block check (when strict).');
w('3. 404 `ACCOUNT_NOT_FOUND` if missing; maintenance blocks non-SUPER_ADMIN.');
w('4. Non-SUPER_ADMIN must be `ACTIVE`.');
w('5. Bad password -> fraud track + 401 `INVALID_CREDENTIALS`.');
w('6. If 2FA enabled -> `{ requires2FA, userId }` without session.');
w('7. Else new `activeSessionId`, issue tokens + CSRF.');
w('8. Single-session: mismatched JWT sessionId -> `SESSION_REPLACED`.');
w('');
w('### 5.4 Refresh Rotation');
w('');
w('1. Load active refresh; on `reuseDetected` revoke entire family.');
w('2. Mark used -> new access + new refresh same family -> revoke old.');
w('3. User must be ACTIVE (or SUPER_ADMIN).');
w('');
w('### 5.5 2FA (TOTP via @otplib)');
w('');
w('- Enable returns QR + 10 bcrypt backup codes; verify-setup enables.');
w('- Login verify with TOTP or backup (consumed).');
w('- Disable requires password.');
w('');
w('### 5.6 Logout / Sessions / Password Reset');
w('');
w('- Logout: revoke refresh (public), clear cookie, clear activeSessionId.');
w('- Logout-all / change-password: revoke all refresh tokens.');
w('- Forgot/reset: opaque responses; revoke all refresh on reset; TTL 1h.');
w('');
w('### 5.7 Authenticated Request Path');
w('');
w('`protect`/`authenticate`: Bearer or `accessToken` cookie -> verify JWT -> load user -> session match -> maintenance/status -> `req.user`.');
w('');
w('---');
w('');
w('## 6. Complete Authorization Matrix');
w('');
w('### 6.1 Roles');
w('');
w('`SUPER_ADMIN | ADMIN | VENDOR | B2B_CUSTOMER | B2C_CUSTOMER | DELIVERY_PARTNER`');
w('');
w('User statuses: `PENDING | ACTIVE | INACTIVE | SUSPENDED | REJECTED`');
w('');
w('### 6.2 Mechanisms');
w('');
w('| Mechanism | Behavior |');
w('|-----------|----------|');
w('| `authorize(...roles)` | Exact role allow-list |');
w('| `requireRole` / `requirePermission` | RBAC; SUPER_ADMIN bypasses permissions |');
w('| `requireOwnershipOr` | Vendor ownership of product |');
w('| `checkResourceQuota` | Soft quotas |');
w('| Feature guards | `allowRegistration`, `enableCOD`, reviews flag |');
w('');
w('### 6.3 Capability Matrix');
w('');
w('| Capability | SA | Admin | Vendor | B2B | DP | Public |');
w('|------------|:--:|:-----:|:------:|:---:|:--:|:------:|');
w('| Register/Login/Reset | Y | Y | Y | Y | Y | Y |');
w('| Platform config / SA admin CRUD / financial analytics | Y | | | | | |');
w('| Bank proof approve/reject | Y | | | | | |');
w('| Admin registration approvals | Y | | | | | |');
w('| Catalog write (categories) | Y | Y | | | | |');
w('| Product write | Y | Y | Y* | | | |');
w('| Inventory admin | Y | Y | Y (update) | | | |');
w('| User approve/reject/status | Y | Y | | | | |');
w('| Order status workflow | Y | Y | | | | |');
w('| Delivery assign | Y | Y | | | | |');
w('| Browse products/search | Y | Y | Y | Y | Y | Y |');
w('| Cart/checkout/wishlist | | | Y | Y | | |');
w('| Credit use | | | Y | Y | | |');
w('| Delivery lifecycle | | | | | Y | |');
w('');
w('\\* Vendor limited to owned products via ownership middleware.');
w('');
w('### 6.4 Soft Quotas');
w('');
w('| Role | Limits |');
w('|------|--------|');
w('| VENDOR | products 1000, orders/day 500, images/product 10 |');
w('| B2B_CUSTOMER | orders/day 100, cart 500 |');
w('| B2C_CUSTOMER | orders/day 10, cart 50 |');
w('| SUPER_ADMIN | bypass |');
w('');
w('---');
w('');

fs.appendFileSync(out, L.join('\n'), 'utf8');
console.log('Part B', fs.statSync(out).size);
