import { useCallback, useEffect, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import superAdminService from '../../services/superAdminService';
import { getUserFacingErrorMessage } from '../../utils/apiResponse';

export default function SupplierProducts() {
  const { supplierId } = useParams();
  const [data, setData] = useState(null); const [search, setSearch] = useState(''); const [status, setStatus] = useState('all'); const [page, setPage] = useState(1); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const load = useCallback(async () => { setLoading(true); setError(''); try { const response = await superAdminService.getSupplierProducts(supplierId, { search, status, page, limit: 20 }); setData(response?.data || response); } catch (err) { setError(getUserFacingErrorMessage(err, 'Unable to load supplier products.')); } finally { setLoading(false); } }, [supplierId, search, status, page]);
  useEffect(() => { load(); }, [load]);
  return <div className="space-y-5"><Link to={`/supplier-dashboard/suppliers/${supplierId}`} className="inline-flex min-h-[44px] items-center text-blue-700">← Back to Supplier</Link><header className="flex flex-wrap items-end justify-between gap-3"><div><h1 className="text-2xl font-bold">Supplier Products</h1><p className="text-sm text-gray-500">Supplier-specific quantity and procurement pricing.</p></div><button type="button" onClick={load} className="min-h-[44px] rounded-lg border px-4">Refresh</button></header><div className="flex flex-wrap gap-3"><input aria-label="Search products" value={search} onChange={(event) => { setSearch(event.target.value); setPage(1); }} className="min-h-[44px] rounded-lg border px-3" placeholder="Product name or SKU"/><select aria-label="Filter status" value={status} onChange={(event) => { setStatus(event.target.value); setPage(1); }} className="min-h-[44px] rounded-lg border px-3"><option value="all">All statuses</option><option value="ACTIVE">Active</option><option value="INACTIVE">Inactive</option></select></div>{error && <div role="alert" className="rounded-lg bg-red-50 p-4 text-red-700">{error} <button onClick={load} className="underline">Retry</button></div>}{loading ? <div role="status" aria-label="Loading supplier products" className="h-48 animate-pulse rounded-xl bg-white" /> : data?.mappings?.length ? <div className="overflow-x-auto rounded-xl border bg-white"><table className="min-w-[800px] w-full text-left text-sm"><thead className="bg-gray-50"><tr>{['Product','SKU','Category','Quantity','Supplier Price','Status','Actions'].map((heading) => <th key={heading} scope="col" className="px-4 py-3 font-semibold">{heading}</th>)}</tr></thead><tbody>{data.mappings.map((row) => <tr key={row._id} className="border-t"><td className="px-4 py-3 font-medium">{row.product?.name}</td><td className="px-4 py-3">{row.product?.sku || '—'}</td><td className="px-4 py-3">{row.product?.category?.name || '—'}</td><td className="px-4 py-3">{Number(row.quantity || 0)}</td><td className="px-4 py-3">{row.currentSupplierPrice == null ? 'Not set' : `₹${Number(row.currentSupplierPrice).toFixed(2)}`}</td><td className="px-4 py-3">{row.availabilityStatus}</td><td className="px-4 py-3">{row.product?.categoryId && <Link className="font-medium text-blue-700" to={`/supplier-dashboard/suppliers/${supplierId}/categories/${row.product.categoryId}`}>Edit / Remove</Link>}</td></tr>)}</tbody></table></div> : <div className="rounded-xl border bg-white p-8 text-center">No supplier products found.</div>}<nav aria-label="Supplier product pagination" className="flex justify-between"><button disabled={page <= 1} onClick={() => setPage((value) => value - 1)}>Previous</button><span>Page {data?.page || 1} of {data?.pages || 1}</span><button disabled={page >= Number(data?.pages || 1)} onClick={() => setPage((value) => value + 1)}>Next</button></nav></div>;
}
