import { useCallback, useEffect, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import superAdminService from '../../services/superAdminService';
import { getUserFacingErrorMessage } from '../../utils/apiResponse';

export default function SupplierProducts() {
 const {supplierId}=useParams(); const [data,setData]=useState(null); const [search,setSearch]=useState(''); const [page,setPage]=useState(1); const [error,setError]=useState('');
 const load=useCallback(async()=>{setError('');try{const r=await superAdminService.getSupplierProducts(supplierId,{search,page,limit:20});setData(r?.data||r);}catch(e){setError(getUserFacingErrorMessage(e,'Unable to load supplier products.'));}},[supplierId,search,page]); useEffect(()=>{load();},[load]);
 return <div className="space-y-5"><Link to={`/supplier-dashboard/suppliers/${supplierId}`} className="text-blue-700">← Back to Supplier</Link><header><h1 className="text-2xl font-bold">Supplier Products</h1><p className="text-sm text-gray-500">All products supplied by this supplier. Add products from an associated category.</p></header><div className="flex flex-wrap gap-2"><input aria-label="Search products" value={search} onChange={e=>{setSearch(e.target.value);setPage(1);}} className="min-h-[44px] rounded-lg border px-3" placeholder="Product name or SKU"/><button onClick={load} className="min-h-[44px] rounded-lg border px-4">Refresh</button></div>{error&&<div role="alert">{error} <button onClick={load}>Retry</button></div>}<div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{data?.mappings?.map(row=><article key={row._id} className="rounded-xl border bg-white p-5"><h2 className="font-semibold">{row.product?.name}</h2><p className="text-sm text-gray-500">{row.product?.sku}</p><dl className="mt-3 text-sm"><dt>Category</dt><dd>{row.product?.category?.name||'—'}</dd><dt>Quantity</dt><dd>{row.quantity||0}</dd><dt>Supplier Price</dt><dd>{row.currentSupplierPrice==null?'Not set':`₹${Number(row.currentSupplierPrice).toFixed(2)}`}</dd><dt>Status</dt><dd>{row.availabilityStatus}</dd></dl>{row.product?.categoryId&&<Link className="mt-4 inline-block text-blue-700" to={`/supplier-dashboard/suppliers/${supplierId}/categories/${row.product.categoryId}`}>Edit / Remove</Link>}</article>)}</div>{data&&!data.mappings?.length&&<div className="rounded-xl border bg-white p-8 text-center">No supplier products found.</div>}<div className="flex justify-between"><button disabled={page<=1} onClick={()=>setPage(p=>p-1)}>Previous</button><span>Page {data?.page||1} of {data?.pages||1}</span><button disabled={page>=Number(data?.pages||1)} onClick={()=>setPage(p=>p+1)}>Next</button></div></div>;
}
