import { useCallback, useEffect, useState } from 'react';
import { FiDownload, FiPlus, FiTrash2 } from 'react-icons/fi';
import PageHeader from '../../components/superadmin/PageHeader';
import DataTable from '../../components/superadmin/DataTable';
import Modal from '../../components/superadmin/Modal';
import superAdminService from '../../services/superAdminService';
import { getUserFacingErrorMessage } from '../../utils/apiResponse';

const TYPES = ['GST_CERTIFICATE','PAN','COMPANY_REGISTRATION','BUSINESS_LICENSE','TRADE_LICENSE','AGREEMENT','INSURANCE','BANK_DOCUMENT','COMPLIANCE_DOCUMENT','OTHER'];
const input = 'w-full min-h-[44px] rounded-lg border border-gray-300 px-3 py-2 text-sm';
export default function CompanyDocuments() {
  const [rows,setRows]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[search,setSearch]=useState(''),[type,setType]=useState(''),[expiry,setExpiry]=useState('all'),[open,setOpen]=useState(false),[saving,setSaving]=useState(false);
  const [form,setForm]=useState({name:'',type:'GST_CERTIFICATE',description:'',documentNumber:'',issuedDate:'',expiryDate:'',notes:'',file:null});
  const load=useCallback(async()=>{setLoading(true);setError('');try{const r=await superAdminService.getCompanyDocuments({search:search||undefined,type:type||undefined,expiry});const p=r?.data??r;setRows(p?.documents||[]);}catch(e){setError(getUserFacingErrorMessage(e,'Failed to load company documents'));}finally{setLoading(false);}},[search,type,expiry]);
  useEffect(()=>{const id=setTimeout(load,250);return()=>clearTimeout(id);},[load]);
  const submit=async(e)=>{e.preventDefault();setSaving(true);setError('');try{const fd=new FormData();Object.entries(form).forEach(([k,v])=>{if(v)fd.append(k,v);});await superAdminService.uploadCompanyDocument(fd);setOpen(false);setForm({name:'',type:'GST_CERTIFICATE',description:'',documentNumber:'',issuedDate:'',expiryDate:'',notes:'',file:null});await load();}catch(err){setError(getUserFacingErrorMessage(err,'Upload failed'));}finally{setSaving(false);}};
  const download=async(row)=>{try{const response=await superAdminService.downloadCompanyDocument(row._id);const url=URL.createObjectURL(response.data);const a=document.createElement('a');a.href=url;a.download=row.originalName||row.name;a.click();URL.revokeObjectURL(url);}catch(e){setError(getUserFacingErrorMessage(e,'Download failed'));}};
  const archive=async(row)=>{if(!window.confirm(`Archive “${row.name}”?`))return;try{await superAdminService.archiveCompanyDocument(row._id);await load();}catch(e){setError(getUserFacingErrorMessage(e,'Archive failed'));}};
  const columns=[{key:'name',label:'Document'},{key:'type',label:'Type',render:v=>String(v).replaceAll('_',' ')},{key:'uploadedBy',label:'Uploaded By',render:v=>v?.name||'—'},{key:'createdAt',label:'Uploaded On',render:v=>new Date(v).toLocaleDateString('en-IN')},{key:'expiryDate',label:'Expiry',render:v=>v?new Date(v).toLocaleDateString('en-IN'):'No expiry'},{key:'actions',label:'Actions',render:(_,r)=><div className="flex gap-2"><button type="button" onClick={()=>download(r)} className="inline-flex min-h-[44px] items-center gap-1 text-blue-600"><FiDownload/> View / Download</button><button type="button" onClick={()=>archive(r)} className="inline-flex min-h-[44px] items-center gap-1 text-red-600"><FiTrash2/> Archive</button></div>}];
  return <div className="space-y-6"><PageHeader title="Company Documents" subtitle="Private company, legal and compliance documents. Super Admin access only." actions={<button type="button" onClick={()=>setOpen(true)} className="inline-flex min-h-[44px] items-center gap-2 rounded-lg bg-blue-600 px-4 text-white"><FiPlus/> Upload Document</button>}/>{error&&<div className="rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</div>}<div className="flex flex-col gap-3 rounded-xl border bg-white p-4 sm:flex-row"><input className={`${input} flex-1`} placeholder="Search document name" value={search} onChange={e=>setSearch(e.target.value)}/><select className={input} value={type} onChange={e=>setType(e.target.value)}><option value="">All types</option>{TYPES.map(x=><option key={x} value={x}>{x.replaceAll('_',' ')}</option>)}</select><select className={input} value={expiry} onChange={e=>setExpiry(e.target.value)}>{['all','none','active','expiring','expired'].map(x=><option key={x} value={x}>{x[0].toUpperCase()+x.slice(1)}</option>)}</select></div><div className="overflow-x-auto rounded-xl border bg-white p-4">{loading?<p className="text-sm text-gray-500">Loading documents…</p>:rows.length?<DataTable columns={columns} data={rows}/>:<p className="py-10 text-center text-sm text-gray-500">No company documents uploaded.</p>}</div><Modal isOpen={open} onClose={()=>setOpen(false)} title="Upload company document"><form onSubmit={submit} className="space-y-3"><input className={input} required placeholder="Document name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><select className={input} value={form.type} onChange={e=>setForm({...form,type:e.target.value})}>{TYPES.map(x=><option key={x}>{x}</option>)}</select><textarea className={input} placeholder="Description" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/><input className={input} placeholder="Document number (optional)" value={form.documentNumber} onChange={e=>setForm({...form,documentNumber:e.target.value})}/><div className="grid grid-cols-2 gap-3"><label className="text-sm">Issued date<input className={input} type="date" value={form.issuedDate} onChange={e=>setForm({...form,issuedDate:e.target.value})}/></label><label className="text-sm">Expiry date<input className={input} type="date" value={form.expiryDate} onChange={e=>setForm({...form,expiryDate:e.target.value})}/></label></div><input className={input} required type="file" accept=".pdf,.doc,.docx,.jpg,.jpeg,.png,.webp" onChange={e=>setForm({...form,file:e.target.files[0]})}/><textarea className={input} placeholder="Notes (optional)" value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/><button disabled={saving} className="min-h-[44px] w-full rounded-lg bg-blue-600 px-4 text-white disabled:opacity-50">{saving?'Uploading…':'Upload document'}</button></form></Modal></div>;
}
