import { useCallback, useEffect, useState } from 'react';
import PageHeader from '../../components/superadmin/PageHeader';
import DataTable from '../../components/superadmin/DataTable';
import StatusBadge from '../../components/superadmin/StatusBadge';
import superAdminService from '../../services/superAdminService';
import { getUserFacingErrorMessage } from '../../utils/apiResponse';

const input='min-h-[44px] rounded-lg border border-gray-300 px-3 py-2 text-sm';
export default function DeleteRequests(){const[status,setStatus]=useState('PENDING'),[entityType,setEntityType]=useState(''),[rows,setRows]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const load=useCallback(async()=>{setLoading(true);setError('');try{const r=await superAdminService.getDeleteRequests({status:status||undefined,entityType:entityType||undefined});const p=r?.data??r;setRows(p?.requests||[]);}catch(e){setError(getUserFacingErrorMessage(e,'Failed to load delete requests'));}finally{setLoading(false);}},[status,entityType]);useEffect(()=>{load();},[load]);
 const approve=async row=>{if(!window.confirm(`Approve deletion of “${row.entityDisplay}”? Existing safety checks will still run.`))return;try{await superAdminService.approveDeleteRequest(row._id);await load();}catch(e){setError(getUserFacingErrorMessage(e,'Delete approval failed'));}};
 const reject=async row=>{const reason=window.prompt('Rejection reason (required)');if(!reason?.trim())return;try{await superAdminService.rejectDeleteRequest(row._id,reason.trim());await load();}catch(e){setError(getUserFacingErrorMessage(e,'Rejection failed'));}};
 const columns=[{key:'createdAt',label:'Created',render:v=>new Date(v).toLocaleString('en-IN')},{key:'requester',label:'Requester',render:v=>`${v?.name||'—'} (${v?.role||'—'})`},{key:'entityType',label:'Entity'},{key:'entityDisplay',label:'Target'},{key:'reason',label:'Reason',render:v=>v||'—'},{key:'status',label:'Status',render:v=><StatusBadge status={String(v).toLowerCase()}/>},{key:'actions',label:'Review',render:(_,row)=>row.status==='PENDING'?<div className="flex gap-2"><button type="button" onClick={()=>approve(row)} className="min-h-[44px] rounded-lg bg-red-600 px-3 text-white">Approve</button><button type="button" onClick={()=>reject(row)} className="min-h-[44px] rounded-lg border px-3">Reject</button></div>:<span className="text-sm text-gray-500">Reviewed</span>}];
 return <div className="space-y-6"><PageHeader title="Delete Requests" subtitle="Review destructive requests. Approval executes the existing protected deletion or deactivation service."/>{error&&<div className="rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</div>}<div className="flex gap-3 rounded-xl border bg-white p-4"><select className={input} value={status} onChange={e=>setStatus(e.target.value)}><option value="">All statuses</option>{['PENDING','APPROVED','REJECTED','FAILED','STALE'].map(x=><option key={x}>{x}</option>)}</select><select className={input} value={entityType} onChange={e=>setEntityType(e.target.value)}><option value="">All entity types</option>{['PRODUCT','CATEGORY','WAREHOUSE','USER'].map(x=><option key={x}>{x}</option>)}</select></div><div className="overflow-x-auto rounded-xl border bg-white p-4">{loading?<p className="text-sm text-gray-500">Loading requests…</p>:rows.length?<DataTable columns={columns} data={rows}/>:<p className="py-10 text-center text-sm text-gray-500">No delete requests found.</p>}</div></div>}
