import { useCallback, useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { FiBell, FiCheck, FiRefreshCw } from 'react-icons/fi';
import PageHeader from '../../components/superadmin/PageHeader';
import notificationService from '../../services/notificationService';
import { mapNotifications } from '../../utils/deliveryMapper';
import { getUserFacingErrorMessage } from '../../utils/apiResponse';

export default function Notifications(){const navigate=useNavigate();const[rows,setRows]=useState([]),[page,setPage]=useState(1),[pages,setPages]=useState(1),[read,setRead]=useState(''),[category,setCategory]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const load=useCallback(async()=>{setLoading(true);setError('');try{const response=await notificationService.getNotifications({page,limit:20,read:read||undefined,category:category||undefined});const payload=response?.data??response;setRows(mapNotifications(payload?.notifications||[]));setPages(payload?.pagination?.pages||1);}catch(e){setError(getUserFacingErrorMessage(e,'Failed to load notifications'));}finally{setLoading(false);}},[page,read,category]);useEffect(()=>{load();},[load]);
 const open=async item=>{if(!item.read){await notificationService.markAsRead(item.id);setRows(current=>current.map(row=>row.id===item.id?{...row,read:true,isRead:true}:row));}if(item.actionUrl)navigate(item.actionUrl);};
 const allRead=async()=>{await notificationService.markAllAsRead();setRows(current=>current.map(row=>({...row,read:true,isRead:true})));};
 return <div className="space-y-6"><PageHeader title="Notification Center" subtitle="Global business and operational events for Super Admin." actions={<div className="flex gap-2"><button type="button" onClick={allRead} className="inline-flex min-h-[44px] items-center gap-2 rounded-lg border px-3"><FiCheck/> Mark all read</button><button type="button" onClick={load} className="inline-flex min-h-[44px] items-center gap-2 rounded-lg border px-3"><FiRefreshCw/> Refresh</button></div>}/><div className="flex flex-wrap gap-3 rounded-xl border bg-white p-4"><select className="min-h-[44px] rounded-lg border px-3" value={read} onChange={e=>{setRead(e.target.value);setPage(1);}}><option value="">All notifications</option><option value="false">Unread</option><option value="true">Read</option></select><select className="min-h-[44px] rounded-lg border px-3" value={category} onChange={e=>{setCategory(e.target.value);setPage(1);}}><option value="">All categories</option>{['USER','CATALOG','SUPPLIER','ORDER','PAYMENT','LOGISTICS','INVENTORY','SYSTEM'].map(x=><option key={x}>{x}</option>)}</select></div>{error&&<div className="rounded-lg border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}<button type="button" onClick={load} className="ml-2 underline">Retry</button></div>}<div className="space-y-3">{loading?<p className="rounded-xl border bg-white p-8 text-center text-sm text-gray-500">Loading notifications…</p>:rows.length===0?<p className="rounded-xl border bg-white p-8 text-center text-sm text-gray-500">No notifications found.</p>:rows.map(item=><button type="button" key={item.id} onClick={()=>open(item)} className={`flex w-full items-start gap-3 rounded-xl border p-4 text-left ${item.read?'bg-white':'border-blue-200 bg-blue-50'}`}><span className="rounded-lg bg-blue-100 p-2"><FiBell className="text-blue-600"/></span><span className="min-w-0 flex-1"><span className="flex flex-wrap items-center gap-2"><strong className="text-sm">{item.title}</strong><span className="rounded bg-gray-100 px-2 py-0.5 text-[10px]">{item.category}</span><span className="text-[10px] text-gray-500">{item.severity}</span></span><span className="mt-1 block text-sm text-gray-600">{item.message}</span><span className="mt-2 block text-xs text-gray-400">{item.time}</span></span></button>)}</div><div className="flex items-center justify-between"><button disabled={page<=1} onClick={()=>setPage(p=>p-1)} className="min-h-[44px] rounded-lg border px-4 disabled:opacity-40">Previous</button><span className="text-sm">Page {page} of {pages}</span><button disabled={page>=pages} onClick={()=>setPage(p=>p+1)} className="min-h-[44px] rounded-lg border px-4 disabled:opacity-40">Next</button></div></div>}
