import { useCallback, useEffect, useState } from 'react';
import { FiPlus } from 'react-icons/fi';
import PageHeader from '../../components/superadmin/PageHeader';
import DataTable from '../../components/superadmin/DataTable';
import StatusBadge from '../../components/superadmin/StatusBadge';
import Modal from '../../components/superadmin/Modal';
import superAdminService from '../../services/superAdminService';
import { getUserFacingErrorMessage } from '../../utils/apiResponse';

const ROLES=['EXECUTIVE','SWEEPER','CLEANING_STAFF','ACCOUNTANT','STORE_STAFF','WAREHOUSE_STAFF','SECURITY','OTHER']; const input='w-full min-h-[44px] rounded-lg border border-gray-300 px-3 py-2 text-sm';
const empty={name:'',email:'',mobile:'',internalRole:'EXECUTIVE',department:'',joiningDate:'',notes:'',status:'ACTIVE'};
export default function OtherRoles(){const[rows,setRows]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[search,setSearch]=useState(''),[status,setStatus]=useState('all'),[open,setOpen]=useState(false),[saving,setSaving]=useState(false),[form,setForm]=useState(empty);
 const load=useCallback(async()=>{setLoading(true);setError('');try{const r=await superAdminService.getInternalStaff({search:search||undefined,status});const p=r?.data??r;setRows(p?.users||[]);}catch(e){setError(getUserFacingErrorMessage(e,'Failed to load internal staff'));}finally{setLoading(false);}},[search,status]);useEffect(()=>{const id=setTimeout(load,250);return()=>clearTimeout(id);},[load]);
 const submit=async e=>{e.preventDefault();setSaving(true);setError('');try{await superAdminService.createInternalStaff(form);setForm(empty);setOpen(false);await load();}catch(err){setError(getUserFacingErrorMessage(err,'Unable to onboard internal staff'));}finally{setSaving(false);}};
 const toggle=async row=>{try{await superAdminService.updateInternalStaff(row._id,{status:row.status==='ACTIVE'?'INACTIVE':'ACTIVE'});await load();}catch(e){setError(getUserFacingErrorMessage(e,'Unable to update status'));}};
 const columns=[{key:'name',label:'Name'},{key:'internalRole',label:'Role',render:v=>String(v||'').replaceAll('_',' ')},{key:'email',label:'Contact',render:(v,r)=><><div>{v}</div><div className="text-xs text-gray-500">{r.mobile}</div></>},{key:'status',label:'Status',render:v=><StatusBadge status={v.toLowerCase()}/>},{key:'createdAt',label:'Created',render:v=>new Date(v).toLocaleDateString('en-IN')},{key:'access',label:'Access',render:()=> <span className="text-xs text-gray-500">Internal Staff — No platform portal access</span>},{key:'actions',label:'Actions',render:(_,r)=><button type="button" onClick={()=>toggle(r)} className="min-h-[44px] rounded-lg border px-3 text-sm">{r.status==='ACTIVE'?'Deactivate':'Activate'}</button>}];
 return <div className="space-y-6"><PageHeader title="Other Roles" subtitle="Onboard and manage internal staff without granting platform portal permissions." actions={<button type="button" onClick={()=>setOpen(true)} className="inline-flex min-h-[44px] items-center gap-2 rounded-lg bg-blue-600 px-4 text-white"><FiPlus/> Onboard Other Role</button>}/>{error&&<div className="rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</div>}<div className="flex flex-col gap-3 rounded-xl border bg-white p-4 sm:flex-row"><input className={`${input} flex-1`} placeholder="Search staff" value={search} onChange={e=>setSearch(e.target.value)}/><select className={input} value={status} onChange={e=>setStatus(e.target.value)}><option value="all">All status</option><option>ACTIVE</option><option>INACTIVE</option></select></div><div className="overflow-x-auto rounded-xl border bg-white p-4">{loading?<p className="text-sm text-gray-500">Loading internal staff…</p>:rows.length?<DataTable columns={columns} data={rows}/>:<p className="py-10 text-center text-sm text-gray-500">No internal staff found.</p>}</div><Modal isOpen={open} onClose={()=>setOpen(false)} title="Onboard Other Role"><form onSubmit={submit} className="space-y-3">{[['name','Name'],['email','Email'],['mobile','Mobile'],['department','Department (optional)']].map(([k,l])=><input key={k} required={k!=='department'} type={k==='email'?'email':'text'} className={input} placeholder={l} value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})}/>)}<select className={input} value={form.internalRole} onChange={e=>setForm({...form,internalRole:e.target.value})}>{ROLES.map(x=><option key={x}>{x}</option>)}</select><label className="text-sm">Joining date<input className={input} type="date" value={form.joiningDate} onChange={e=>setForm({...form,joiningDate:e.target.value})}/></label><textarea className={input} placeholder="Notes (optional)" value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/><button disabled={saving} className="min-h-[44px] w-full rounded-lg bg-blue-600 text-white disabled:opacity-50">{saving?'Saving…':'Onboard staff'}</button></form></Modal></div>}
