const IMAGES = {
  rice: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=600&auto=format&fit=crop',
  pulses: 'https://images.unsplash.com/photo-1610832958506-aa56368176cf?w=600&auto=format&fit=crop',
  oil: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=600&auto=format&fit=crop',
  spices: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=600&auto=format&fit=crop',
  dryFruits: 'https://images.unsplash.com/photo-1599599810697-829883672c48?w=600&auto=format&fit=crop',
  beverages: 'https://images.unsplash.com/photo-1546173159-315724a25696?w=600&auto=format&fit=crop',
  snacks: 'https://images.unsplash.com/photo-1621939514649-280e2ee25f60?w=600&auto=format&fit=crop',
  dairy: 'https://images.unsplash.com/photo-1628082262854-76366a9a3a6?w=600&auto=format&fit=crop',
};

export const SHOWCASE_CATEGORIES = [
  {
    id: 'showcase-rice',
    name: 'Rice & Grains',
    description: 'Premium rice, wheat, and staple grains for restaurants and retailers.',
    image: IMAGES.rice,
    status: 'active',
  },
  {
    id: 'showcase-pulses',
    name: 'Pulses & Dal',
    description: 'Wholesale lentils and dals sourced for bulk kitchen supply.',
    image: IMAGES.pulses,
    status: 'active',
  },
  {
    id: 'showcase-oil',
    name: 'Cooking Oil',
    description: 'Refined and filtered oils in commercial tins and bulk packs.',
    image: IMAGES.oil,
    status: 'active',
  },
  {
    id: 'showcase-spices',
    name: 'Spices',
    description: 'Ground spices and whole masalas for distributors and caterers.',
    image: IMAGES.spices,
    status: 'active',
  },
  {
    id: 'showcase-dry-fruits',
    name: 'Dry Fruits',
    description: 'Almonds, cashews, raisins, and premium nut assortments.',
    image: IMAGES.dryFruits,
    status: 'active',
  },
  {
    id: 'showcase-beverages',
    name: 'Beverages',
    description: 'Tea, coffee, and beverage concentrates for institutional buyers.',
    image: IMAGES.beverages,
    status: 'active',
  },
  {
    id: 'showcase-snacks',
    name: 'Snacks',
    description: 'Namkeen, biscuits, and packaged snacks for retail chains.',
    image: IMAGES.snacks,
    status: 'active',
  },
  {
    id: 'showcase-dairy',
    name: 'Dairy Products',
    description: 'Ghee, milk powder, paneer, and dairy essentials in bulk.',
    image: IMAGES.dairy,
    status: 'active',
  },
];

export const SHOWCASE_PRODUCTS = [
  {
    id: 'showcase-product-rice',
    name: 'Sona Masoori Rice 25kg',
    category: 'Rice & Grains',
    price: 1350,
    moq: 10,
    minOrderQty: 10,
    image: IMAGES.rice,
    imageUrl: IMAGES.rice,
  },
  {
    id: 'showcase-product-dal',
    name: 'Toor Dal Premium',
    category: 'Pulses & Dal',
    price: 1550,
    moq: 5,
    minOrderQty: 5,
    image: IMAGES.pulses,
    imageUrl: IMAGES.pulses,
  },
  {
    id: 'showcase-product-oil',
    name: 'Refined Sunflower Oil 15L',
    category: 'Cooking Oil',
    price: 1750,
    moq: 5,
    minOrderQty: 5,
    image: IMAGES.oil,
    imageUrl: IMAGES.oil,
  },
  {
    id: 'showcase-product-spice',
    name: 'Turmeric Powder Premium',
    category: 'Spices',
    price: 780,
    moq: 5,
    minOrderQty: 5,
    image: IMAGES.spices,
    imageUrl: IMAGES.spices,
  },
];
