import React, { useEffect, useState } from 'react';
import warehouseService from '../../services/warehouseService';

const unwrap = (payload) => payload?.data ?? payload;

export default function WarehouseOriginPanel() {
  const [warehouse, setWarehouse] = useState(null);
  const [form, setForm] = useState({ name: '', address: '', latitude: '', longitude: '' });
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [message, setMessage] = useState('');
  const [error, setError] = useState('');
  useEffect(() => { warehouseService.list().then((payload) => { const rows = unwrap(payload) || []; const origin = rows.find((row) => row.isDeliveryOrigin) || rows[0]; setWarehouse(origin || null); setForm({ name: origin?.name || '', address: origin?.location?.address || '', latitude: origin?.location?.coordinates?.latitude ?? '', longitude: origin?.location?.coordinates?.longitude ?? '' }); }).catch((loadError) => setError(loadError?.response?.data?.message || 'Unable to load warehouses.')).finally(() => setLoading(false)); }, []);
  const save = async () => { setSaving(true); setError(''); setMessage(''); try { const latitude = Number(form.latitude); const longitude = Number(form.longitude); if (!form.name.trim() || !form.address.trim() || !Number.isFinite(latitude) || latitude < -90 || latitude > 90 || !Number.isFinite(longitude) || longitude < -180 || longitude > 180) throw new Error('Name, address, and valid coordinates are required.'); const payload = { name: form.name.trim(), isActive: true, isDeliveryOrigin: true, location: { address: form.address.trim(), coordinates: { latitude, longitude } } }; const saved = unwrap(await warehouseService.update(warehouse._id, payload)); setWarehouse(saved); setMessage('Client warehouse pickup location saved.'); } catch (saveError) { setError(saveError?.response?.data?.message || saveError?.message || 'Unable to save warehouse.'); } finally { setSaving(false); } };
  if (loading) return <div className="rounded-lg border bg-white p-4 text-sm text-gray-500">Loading warehouse location...</div>;
  return <div className="rounded-lg border bg-white p-4 sm:p-6 space-y-4"><div><h2 className="text-base font-semibold text-gray-900">Warehouse Pickup Location</h2><p className="text-xs text-gray-500 mt-1">The configured warehouse is the canonical Delivery Partner origin.</p></div>{error && <p role="alert" className="text-sm text-red-700">{error}</p>}{message && <p className="text-sm text-green-700">{message}</p>}{warehouse ? <><label className="block text-sm">Name<input value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} className="mt-1 w-full rounded border px-3 py-2" /></label><label className="block text-sm">Address<input value={form.address} onChange={(e) => setForm({ ...form, address: e.target.value })} className="mt-1 w-full rounded border px-3 py-2" /></label><div className="grid grid-cols-1 sm:grid-cols-2 gap-3"><label className="block text-sm">Latitude<input type="number" min="-90" max="90" step="any" value={form.latitude} onChange={(e) => setForm({ ...form, latitude: e.target.value })} className="mt-1 w-full rounded border px-3 py-2" /></label><label className="block text-sm">Longitude<input type="number" min="-180" max="180" step="any" value={form.longitude} onChange={(e) => setForm({ ...form, longitude: e.target.value })} className="mt-1 w-full rounded border px-3 py-2" /></label></div><button type="button" onClick={save} disabled={saving} className="min-h-[44px] rounded-lg bg-blue-600 px-4 py-2 text-sm font-medium text-white disabled:bg-gray-300">{saving ? 'Saving...' : 'Save'}</button></> : <p className="text-sm text-amber-700">Create a warehouse first before configuring the delivery origin.</p>}</div>;
}
